### ISSUE TITLE
[Question] Is there a synchronous mode?

### ISSUE THREAD

**Issue by rslifka** [KrisSiegel/msngr.js#67]
Handful of pub/sub libraries out there and this is the most active one (thank you! :) Is there a synchronous dispatch mode? `postal.js` worked synchronously but isn't actively maintained and didn't play nicely with`jasmine-jquery`. Currently using `PubSub.js` which offers `publish.publishSync`. I searched through `msngr` and didn't find anything obvious.

**Comment by KrisSiegel** [comment]
Sorry, just seeing this question now!

There is no way to do synchronous message handling in msngr by design. Since not all subscribers are equal and some may run long, if you have to process multiple of these per publish event you may cause considerable jank in your web app by not freeing up the JavaScript scheduler after each event.

I thought about adding a synchronous mode in the past but felt it complicated the code for no (or possibly negative) benefit. I'm not familiar with `jasmine-query` but I know `jasmine` itself can run asynchronously so I'm curious if there is a different solution to your problem.

Hope that helps!

**Comment by rslifka** [comment]
Thank you @KrisSiegel! The only reason I ask is that I'm not sure how to handle expectations in testing if I need to wait for events. I'm a bit new to full-on JS apps and what I'm working on is a UserScript (https://github.com/rslifka/fate_of_all_fools), but my general pattern is this:

```
pubsub.publishSync(...);
// Event is handled by the module under test
// Module modifies the DOM in some way
expect($(...)).toContainElement(...);
```

...and so I'm not quite sure what to do in this case where I want to treat the handling as a black box and test the observable outcomes. Happy to dive in to some resources that discuss but I only really find information about what to do if you want to test something itself that is asynchronous (e.g. Promises).

I'll close this out for now; hopefully helpful to someone Googling :) Thanks again for your response and your efforts on msngr!

**Comment by KrisSiegel** [comment]
Hey, so it sounds like you need to handle things more asynchronously. For example when testing in `mocha` you can do something like:

```javascript
it("My test", function (done) {
    $("#myelement").on("change", function (e) {
        expect(/* whatever */);
        done();
    });
    msngr("publish").emit();
});
```

Hope that helps

**Comment by rslifka** [comment]
It does, thank you!
