### ISSUE TITLE
done.apply is not a function

### ISSUE THREAD

**Issue by hyyan** [KrisSiegel/msngr.js#68]
Howdy

I am completely new to this lib and I am trying to get my head around it, 
While playing around I came across this issue 

```js 
const getPromise = (message , time = 100) => {
  return new Promise((resolve,reject) => {
        
      setTimeout(() => {
        console.log(message)
        resolve(message);
      },time);
      
    });
}

msngr("Message 1").on((message) => {
   return getPromise(message) 
});

msngr("Message 1").emit("I'm chainable!" , 300);
msngr("Message 1").emit("Another!");
  
```

The console log is : 

```
Uncaught TypeError: done.apply is not a function
    at msngr.js:669
    at msngr.js:640
    at msngr.js:273

"I'm chainable!"
"Another!"
```

now if I change the emit code to the following the error disappear. Strange!

```js
msngr("Message 1").emit("I'm chainable!");
msngr("Message 1").emit("Another!");
```
Any idea ?!
Thanks

**Comment by KrisSiegel** [comment]
Hey @hyyan! Thanks for checking it out! As for your particular issue that's because the second parameter is an optional callback so you can get a response once your emit has been received and processed by all subscribed handlers. Here's an example: https://jsfiddle.net/w0agynge/

If you're trying to add `300` as simply more data I would suggest creating some sort of object to instead instead. So maybe:

```javascript
msngr("Message 1").on((payload) => {
    console.log(payload);
});

msngr("Message 1").emit({
    text: "I'm chainable!",
    num: 300
});
```

Hope that helps. Perhaps I should look into providing better error messages / warnings based on the types of passed in content so this is more intuitive.

**Comment by hyyan** [comment]
@KrisSiegel Great , thanks for the clarification
